# Generated by Django 3.2.5 on 2021-08-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_rename_cliente_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='foto',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
